### ISSUE TITLE
Script Name Variable Won't Apply

### ISSUE THREAD

**Issue by AFilthyLeaf** [mikecao/umami#1000] opened 2022-03-01 03:45 UTC
I am running this on Heroku, I added `TRACKER_SCRIPT_NAME` to my config vars, with the value `viewcount` and restarted all dyno's. Even after the restart the script doesn't work at the `viewcount` location.

**Comment by mikecao** [comment] 2022-03-01 04:18
In the current version you need to rebuild the app for it to apply, sorry. In the next release it should work at runtime as intended.

**Comment by mikecao** [comment] 2022-03-03 05:53
Fixed in v1.27.0

**Closed by mikecao** 2022-03-03 05:53 UTC
Labels: bug, fixed in dev
