### ISSUE TITLE
Can this support SQLite?

### ISSUE THREAD

**Issue by paperrgb** [mikecao/umami#539] opened 2021-03-11 19:13 UTC
Is there a way to get this to use SQLite instead of Postgres?

**Comment by mikecao** [comment] 2021-03-12 03:39
It's possible because Prisma does support SQLite. But we would have to rewrite all the custom queries to support it. I don't have the time bandwidth to implement it. If someone wants to do it and submit a PR, I can take a look.

**Comment by thomasrosen** [comment] 2021-03-15 01:00
Duplicate of #245

**Closed** 2021-03-15 03:20 UTC
