### ISSUE TITLE
Tracking Events not registering

### ISSUE THREAD

**Issue by threesam** [mikecao/umami#477] opened 2021-02-15 17:46 UTC
Using the CSS method of tracking (inside of a Svelte app) on my links, the classes are assigned correctly but no data is showing up in the dashboard. Any suggestions on debugging or config? Thanks so much!

**Comment by mikecao** [comment] 2021-02-15 21:08
What does your css class look like?

**Comment by threesam** [comment] 2021-02-15 21:38
"umami--click--github-social" and the id is "github-social"

**Comment by mikecao** [comment] 2021-02-16 21:18
Are you placing it on a link? I believe Chrome has issues with firing events on links that take you to another domain.

**Comment by threesam** [comment] 2021-02-17 18:19
Yeah, mostly external links and one internal--none registered. I was testing on firefox, so I guess that's a wider browser issue that the JS implementation, over CSS classes, wouldn't necessarily sidestep?

**Comment by mikecao** [comment] 2021-02-17 21:46
Sorry, I got my browsers mixed up, Firefox is the one that doesn't record events on links. I'll have to do more research to see if we can get around it.

**Comment by mikecao** [comment] 2021-02-27 07:07
Closing as duplicate of #507. Will track issues there.

**Closed by mikecao** 2021-02-27 07:07 UTC
Labels: bug
