### ISSUE TITLE
custom tracker name not working

### ISSUE THREAD

**Issue by Silocoxyz** [mikecao/umami#1049] opened 2022-03-22 20:40 UTC
I've added the environment variable "TRACKER_SCRIPT_NAME" with the value of "t" (on vercel) but the script name is still umami.js

What can I do? Should I just change all references of umami.js to t.js ?

**Comment by MagicLike** [comment] 2022-03-23 13:24
First of all, yes you have to change all `umami.js` to `t.js`, because the name of the script is changed, by adding this environment variable.
If it is still not working, try rebuilding the project on Vercel.
I hope it works!

**Comment by mikecao** [comment] 2022-03-23 18:35
In Vercel, if you add an environment variable, you have to redeploy or it won't pick it up.

**Comment by rdgout** [comment] 2022-03-28 13:10
@mikecao it looks like there was a regression somewhere.
In the latest version the code to generate the file was actually removed.

https://github.com/mikecao/umami/compare/v1.26.0...v1.27.0
It already happened in 1.27.0 and to be exact it was this commit: https://github.com/mikecao/umami/commit/460762bf3d11b6e3938fa1270e807bc43a8f75a4

**Comment by laurent-d** [comment] 2022-03-28 20:59
Same issue on Netlify, re-deployed too

**Comment by mikecao** [comment] 2022-03-29 05:00
@rdgout That method was abandoned because it only worked during build time (which doesn't work for docker images). In v1.28.0 it uses middleware during runtime.

@laurent-d I've never been able to deploy to Netlify successfully. But it been a while since I've tried so I'll probably revisit at some point.

**Comment by Silocoxyz** [comment] 2022-03-29 23:03
> In Vercel, if you add an environment variable, you have to redeploy or it won't pick it up.

I have redeployed, removed/added EV, but it is not working.

**Comment by Silocoxyz** [comment] 2022-03-29 23:08
> @rdgout That method was abandoned because it only worked during build time (which doesn't work for docker images). In v1.28.0 it uses middleware during runtime.
> 
> @laurent-d I've never been able to deploy to Netlify successfully. But it been a while since I've tried so I'll probably revisit at some point.

What is the best way to achieve this? Change all instances of umami.js to customName.js?

**Comment by mikecao** [comment] 2022-03-29 23:40
@Silocoxyz are you sure you're running v1.28.0? That's where the middleware feature landed.

**Comment by TwoThreeWang** [comment] 2022-04-03 14:11
After setting the variable, umami.js can be accessed, and the custom name can also be accessed. Both are valid at the same time.

**Comment by HaruMiyaGi** [comment] 2022-04-08 16:50
I think the misunderstanding is, (which I also had and was confused about) is that the `TRACKER_SCRIPT_NAME` would change the name of the `umami.js` file, when it actually acts as a redirect to it? Maybe changing .env value name to something like `ALTERNATIVE_SCRIPT_NAME` would clear this up more.

**Closed** 2022-05-07 04:07 UTC

**Comment by igorkulman** [comment] 2022-05-09 08:28
Same problem on Netlify, fresh fork so 1.31, set TRACKER_SCRIPT_NAME=u, did a new deploy also clearing the cache but /u.js is not accessible

**Comment by MatthK** [comment] 2022-05-30 09:51
I also just tried this in a docker container. The ENV variable is set to TRACKER_SCRIPT_NAME=u.js but /u.js is not accessible, while umami.js still is.

It runs the latest v1.31.0.

**Comment by Qnemes** [comment] 2024-07-06 23:02
Same problem on Netlify for me, while COLLECT_API_ENDPOINT works just fine.
